{{- if .Values.authSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authSecret.name }}
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/part-of: caring
type: Opaque
stringData:
  access_token: {{ required "authSecret.accessToken is required when authSecret.create=true" .Values.authSecret.accessToken | quote }}
{{- end }}
