{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: github-runner
    app.kubernetes.io/part-of: caring
{{- end }}
