apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authorization-policy-external-allow-public-access-dev
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: gateway-external-dev
  action: ALLOW
  rules:
    - to:
        - operation:
            notPaths:
              [
                "/V1",
                "/V1/",
                "/V1/*",

                "/V2",
                "/V2/",
                "/V2/*",

                "/V3",
                "/V3/",
                "/V3/*",
              ]
