apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-caring-web-page
spec:
  replicas: {{ .Values.App.Replicas }}
  selector:
    matchLabels:
      app: new-caring-web-page
  template:
    metadata:
      labels:
        app: new-caring-web-page
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
        - name: new-caring-web-page
          image: "asia-east1-docker.pkg.dev/jubo-care-platform/jcp-docker-registry/jcp-react-frontend-share:{{ .Values.App.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: new-caring-web-page-config
          ports:
            - containerPort: 3000
          resources:
{{ toYaml .Values.App.AppResources | indent 11 }}