{{- if .Values.imagePullSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"_json_key\",\"password\":%s,\"email\":\"not-used@example.com\"}}}" .Values.imagePullSecrets.registry (.Values.imagePullSecrets.credential | toJson) | b64enc }}
{{- end }}