apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"80":"neg-name"},"zones":["asia-east1-a,asia-east1-b,asia-east1-c"]}'
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
