{{- if and .Values.Settings.UseStorage .Values.Settings.Urls.ReleaseBackendApiCaringStorage }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: new-caring-web-api-storage-release
  namespace: istio-system
spec:
  hosts:
    - {{ .Values.Settings.Urls.ReleaseBackendApiCaringStorage }}
  gateways:
    - istio-system/infra-gateway
  http:
    - rewrite:
        authority: storage.googleapis.com
      route:
        - destination:
            host: storage.googleapis.com
            port:
              number: 443
{{ end }}