apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: new-caring-web-api-internal-qat
  namespace: istio-system
spec:
  hosts:
    - "upgrade-qat-01.caringcm.com.tw"
    - "upgrade-qat-02.caringcm.com.tw"
  gateways:
    - istio-system/infra-gateway-internal-qat
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: new-caring-web-api.new-caring-web-api-qat.svc.cluster.local
            port:
              number: 80
