apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: maintenance-page-proxy-neg-dev
  namespace: istio-system
spec:
  hosts:
    - "*.caringcm.com.tw"
  gateways:
    - istio-system/infra-gateway-neg-dev
  http:
    - match:
        - uri:
            exact: /maintenance
        - uri:
            prefix: /maintenance/
      route:
        - destination:
            host: maintenance-page-proxy.new-caring-maintenance-page.svc.cluster.local
            port:
              number: 80
