apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: new-caring-web-page-neg-qat
  namespace: istio-system
spec:
  hosts:
    - "upgrade-qat-01.caringcm.com.tw"
    - "upgrade-qat-02.caringcm.com.tw"
  gateways:
    # - istio-system/infra-gateway-neg-qat
    - istio-system/infra-gateway-neg-dev
  http:
    - match:
        - uri:
            prefix: /v2
      route:
        - destination:
            host: new-caring-web-page.new-caring-web-page-qat.svc.cluster.local
            port:
              number: 80
