apiVersion: v1
kind: Secret
metadata:
  name: new-caring-git-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  password: Z2xwYXQtRVIyd2FKWkxzQXM0ZEQ5aWhWZWo=
  project: ZGVmYXVsdA==
  type: Z2l0
  url: aHR0cHM6Ly9naXRsYWIuc21hcnQtYWdpbmcudGVjaC9jYXJpbmdjbS9uZXctY2FyaW5nL21hbmlmZXN0LmdpdA==
  username: bmV3LWNhcmluZy1hcmdvY2Q=
type: Opaque
