apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: new-caring-web-page-demo
  namespace: istio-system
spec:
  hosts:
    - "new-caring-demo.jubo.health"
  gateways:
    - istio-system/infra-gateway-external-demo
  http:
    - route:
        - destination:
            host: new-caring-web-page.new-caring-web-page-demo.svc.cluster.local
            port:
              number: 80
