apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: new-caring-web-page-dev
  namespace: istio-system
spec:
  hosts:
    - "new-caring-dev.jubo.health"
  gateways:
    - istio-system/infra-gateway-external-dev
  http:
    - route:
        - destination:
            host: new-caring-web-page.new-caring-web-page-dev.svc.cluster.local
            port:
              number: 80
