App:
  Replicas: 3
  Version: 3.3.323caring
  ConfigMap:
    Data:
      DEPLOY: release
  AppResources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
