App:
  Replicas: 1
  Version: 2.1.44-caring
  ConfigMap:
    Data:
      DEPLOY: dev
  AppResources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1280Mi
