App:
  Replicas: 3
  Version: 2.1.41-caring
  ConfigMap:
    Data:
      DEPLOY: release
  AppResources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
