App:
  Replicas: 1
  Version: 3.0.39-caring
  ConfigMap:
    Data:
      DEPLOY: demo
  AppResources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1280Mi
