App:
  Replicas: 1
  Version: 3.1.48-caring
  ConfigMap:
    Data:
      DEPLOY: qat
  AppResources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1280Mi
