App:
  Replicas: 1
  Version: 3.6.21-caring
  ConfigMap:
    Data:
      DEPLOY: dev3
  AppResources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 1000m
      memory: 1280Mi
