App:
  Replicas: 1
  Version: 3.6.22-caring
  ConfigMap:
    Data:
      DEPLOY: qat
  AppResources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 1000m
      memory: 1280Mi
