App:
  Replicas: 1
  Version: 2.0.12-caring
  ConfigMap:
    Data:
      DEPLOY: demo
  AppResources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1280Mi
