apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: infra-gateway-internal-release
  namespace: istio-system
spec:
  selector:
    istio: gateway-internal-release
  servers:
    - hosts:
        - "*.caringcm.com.tw"
      port:
        name: http
        number: 80
        protocol: HTTP
