apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: new-caring-web-page-internal-release
  namespace: istio-system
spec:
  hosts:
    - "*.caringcm.com.tw"
  gateways:
    - istio-system/infra-gateway-internal-release
  http:
    - match:
        - uri:
            prefix: /v2
      route:
        - destination:
            host: new-caring-web-page.new-caring-web-page-release.svc.cluster.local
            port:
              number: 80
