apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: new-caring-mobile-api-neg-qat
  namespace: istio-system
spec:
  hosts:
    - "mobile-api-qat.caringcm.com.tw"
  gateways:
    - istio-system/infra-gateway-neg-dev
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: new-caring-mobile-api.new-caring-mobile-api-qat.svc.cluster.local
            port:
              number: 80
