apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: new-caring-web-page-neg-demo
  namespace: istio-system
spec:
  hosts:
    - "dctest.caringcm.com.tw"
    - "erstest.caringcm.com.tw"
    - "mgmt.caringcm.com.tw"
    - "mgmtsmc.caringcm.com.tw"
    - "mgmttest.caringcm.com.tw"
    - "mini-test.caringcm.com.tw"
    - "sjtest.caringcm.com.tw"
    - "sso-demo.caringcm.com.tw
    - "sso-dev.caringcm.com.tw"
    - "test.caringcm.com.tw"
    - "test00.caringcm.com.tw"
  gateways:
    - istio-system/infra-gateway-neg
  http:
    - match:
        - uri:
            prefix: /v2
      route:
        - destination:
            host: new-caring-web-page.new-caring-web-page-demo.svc.cluster.local
            port:
              number: 80
