kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Chart.Name }}-config"
data:
  ASPNETCORE_ENVIRONMENT: "{{ .Values.App.Env }}"
  ConnectionStrings__CaringDbContext: "{{ .Values.App.ConnectionStrings.CaringDbContext }}"
  ConnectionStrings__CHomeConnection: "{{ .Values.App.ConnectionStrings.CHomeConnection }}"
  ConnectionStrings__OldCaringConnection: "{{ .Values.App.ConnectionStrings.OldCaringConnection }}"
  OpenTelemetry__EndPoint: "{{ .Values.App.OpenTelemetry.EndPoint }}"
  OpenTelemetry__Protocol: "{{ .Values.App.OpenTelemetry.Protocol }}"
  CloudPubSub__ProjectId: "{{ .Values.App.CloudPubSub.ProjectId }}"
  CloudPubSub__TopicId: "{{ .Values.App.CloudPubSub.UserActivityLogTopicId }}"
  CloudPubSub__UserActivityLogSubscriptionId: "{{ .Values.App.CloudPubSub.UserActivityLogTopicId }}-sub"
  CloudPubSub__UserEventHandlingTopicId: "{{ .Values.App.CloudPubSub.UserEventHandlingTopicId }}"
  CloudPubSub__UserEventHandlingSubscriptionId: "{{ .Values.App.CloudPubSub.UserEventHandlingSubscriptionId }}-sub"
  JCP__EndPoint: "{{ .Values.App.JCP.EndPoint }}"
  JCP__Ca: "{{ .Values.App.JCP.Ca }}"
  JCP__Cs: "{{ .Values.App.JCP.Cs }}"
  JCP__CaringEndPoint: "{{ .Values.App.JCP.CaringEndPoint }}"
  JCP__SSOUrl: "{{ .Values.App.JCP.SSOUrl }}"
  JCP__CloudPubSub__ProjectId: "{{ .Values.App.JCP.CloudPubSub.ProjectId }}"
  JCP__CloudPubSub__OrganizationEventHandlingSubscriptionId: "{{ .Values.App.JCP.CloudPubSub.OrganizationEventHandlingSubscriptionId }}"
  JCP__CloudPubSub__JcpUserEventHandlingSubscriptionId: "{{ .Values.App.JCP.CloudPubSub.JcpUserEventHandlingSubscriptionId }}"
  JCP__CloudPubSub__JcpUserPrivilegeEventHandlingSubscriptionId: "{{ .Values.App.JCP.CloudPubSub.JcpUserPrivilegeEventHandlingSubscriptionId }}"