App:
  Replicas: 1
  Version: 2.1.5.7-dev3-1
  UseHPA: false
  UsePDB:
    enabled: false
    UseUnavailable: false # use this should set replicas to 2 above
  ContainerPort: 8080
  ServiceAccount: "n-c-b-a@static-map-242406.iam.gserviceaccount.com"
  AppResources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 1000m
      memory: 1280Mi
  ConnectionStrings:
  ConnectionStrings:
    PostgreSqlMaster: "Server=127.0.0.1;Port=5432;Database=caring_dev;Userid=n-c-b-a@static-map-242406.iam;Pooling=true;MinPoolSize=1;MaxPoolSize=100;ConnectionLifeTime=60;"
    PostgreSqlSlave: "Server=127.0.0.1;Port=5432;Database=caring_dev;Userid=n-c-b-a@static-map-242406.iam;Pooling=true;MinPoolSize=1;MaxPoolSize=100;ConnectionLifeTime=60;"
    CHomeConnection: "Server=10.140.15.234,9900;Database=CHOME;User Id=sso_admin;Password=5086@Jubo_SSO@8012;TrustServerCertificate=true;"
    OldCaringConnection: "Server={SERVER},{PORT};Database={DBNAME};User Id=sso_admin;Password=5086@Jubo_SSO@8012;TrustServerCertificate=true;"
  OpenIdConnect:
    Authority: "https://localhost:5001"
    ClientId: "caring-web-dev3"
    ClientSecret: "dev3-secret"
    ResponseType: "code"
    Scope: "openid profile email"
    CallbackPath: "/signin-oidc"
    SignedOutCallbackPath: "/signout-callback-oidc"
    SaveTokens: true
    GetClaimsFromUserInfoEndpoint: true
    RequireHttpsMetadata: false
  Redis:
    ConnectionString: "jubo-mqtt.asia-east1-b.c.static-map-242406.internal:6379,defaultDatabase=5"

SqlProxy:
  Version: 2.18.1
  InstanceName: static-map-242406:asia-east1:caring-dev-pg
  SqlProxyResources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 512Mi
