{{- if .Values.frontendConfig.enabled -}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: new-caring-frontend-config
spec:
  redirectToHttps:
    enabled: {{ .Values.frontendConfig.spec.redirectToHttps.enabled }}
    responseCodeName: {{ .Values.frontendConfig.spec.redirectToHttps.responseCodeName }} # 可選: MOVED_TEMPORARILY_DEFAULT
  {{- if .Values.frontendConfig.spec.redirectToHttps.enabled -}}
  sslPolicy: "new-caring-ssl-policy" # 預定義的或自定義的 SSL 策略名稱
  hsts:
    enabled: {{ .Values.frontendConfig.spec.redirectToHttps.enabled }}
    maxAge: "31536000" # 1年(秒)
    includeSubDomains: {{ .Values.frontendConfig.spec.redirectToHttps.enabled }}
    preload: {{ .Values.frontendConfig.spec.redirectToHttps.enabled }}
  {{- end }}
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 3600
  timeoutSec: 30 # 默認後端服務超時(秒)
  connectionDraining:
    drainingTimeoutSec: 60
{{- end }}