# Infrastructure/argocd/values.yaml
argo-cd:
  global:
    domain: new-caring-argocd.jubo.health
    logging:
      format: json # 預設是 text
      level: info
  crds:
    install: false
  configs:
    rbac:
      policy.default: "role:admin"
    cm:
      # 修正 oidc: expected audience "argo-cd-cli" got ["argo-cd"]" 錯誤
      dex.config: |
        connectors:
          - type: microsoft
            id: microsoft
            name: Microsoft
            config:
              clientID: "50b6ed34-b030-4104-a14d-c8bc139b7d2b"
              clientSecret: $argocd-dex-ms-secret:clientSecret
              tenant: "organizations"
              hostedDomains: ["jubo.health"]
              allowedAudiences:
                - argo-cd
                - argo-cd-cli

    params:
      # 告訴 ArgoCD 不要自己在內部強制轉跳 HTTPS，交給 Gateway 處理
      server.insecure: true

      # 確保了 Helm chart 的所有後續部署都強制 dex 使用 http endpoint 而不是 https endpoint
      dexserver.disable.tls: true
      server.dex.server.strict.tls: false
      server.dex.server: http://argocd-dex-server:5556

  server:
    service:
      annotations:
        # 提供 neg 接口給自建的 LB 整合
        cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "new-caring-argocd-80"}}}'

  # 不要對 SecretInit 注入 sidecar, 會導致 job 無法結束
  redisSecretInit:
    podLabels:
      sidecar.istio.io/inject: "false"

  # TODO 將 Azure Group 對應至 ArgoCD 權限
  #rbac:
  #  policy.csv: |
  #    g, "Azure-Admins-Group-ID", role:admin
  #    g, "Azure-Dev-Group-ID", role:readonly

# 簡化版本的 argocd apps, 去除掉重複的設定
apps:
  global:
    repoURL: https://gitlab.smart-aging.tech/caringcm/new-caring/manifest.git
    targetRevision: main

  # -- Deploy Argo CD Applications within this helm release
  applications:
    # argocd
    argocd:
      syncWave: "-20"
      sourcePath: Infrastructure/argocd
      destinationNamespace: argocd
      extraSyncOptions:
        - RespectIgnoreDifferences=true
      ignoreReplicasDifferences: false

    # dev ↓↓↓

    # Caring
    new-caring-web-api-dev:
      sourcePath: Microservices/Caring/Backend/Api/new-caring-web-api
      sourceHelm:
        valueFiles:
          - values_dev.yaml
      destinationNamespace: new-caring-web-api-dev
      ignoreReplicasDifferences: false

    new-caring-web-api-dev2:
      sourcePath: Microservices/Caring/Backend/Api/new-caring-web-api
      sourceHelm:
        valueFiles:
          - values_dev2.yaml
      destinationNamespace: new-caring-web-api-dev2
      ignoreReplicasDifferences: false

    new-caring-web-api-dev3:
      sourcePath: Microservices/Caring/Backend/Api/new-caring-web-api
      sourceHelm:
        valueFiles:
          - values_dev3.yaml
      destinationNamespace: new-caring-web-api-dev3
      ignoreReplicasDifferences: false

    new-caring-web-dev3:
      sourcePath: Microservices/Caring/Frontend/Web
      sourceHelm:
        valueFiles:
          - values_dev3.yaml
      destinationNamespace: new-caring-web-dev3
      ignoreReplicasDifferences: false

    new-caring-web-page-dev:
      sourcePath: Microservices/Caring/Frontend/Page/new-caring-web-page
      sourceHelm:
        valueFiles:
          - values_dev.yaml
      destinationNamespace: new-caring-web-page-dev
      ignoreReplicasDifferences: false

    new-caring-web-page-dev3:
      sourcePath: Microservices/Caring/Frontend/Page/new-caring-web-page
      sourceHelm:
        valueFiles:
          - values_dev3.yaml
      destinationNamespace: new-caring-web-page-dev3
      ignoreReplicasDifferences: false

    new-caring-mobile-api-dev:
      sourcePath: Microservices/Caring/Backend/Api/new-caring-mobile-api
      sourceHelm:
        valueFiles:
          - values_dev.yaml
      destinationNamespace: new-caring-mobile-api-dev
      ignoreReplicasDifferences: false

    new-caring-event-consumer-dev:
      sourcePath: Microservices/Caring/Event/Consumer/new-caring-event-consumer
      sourceHelm:
        valueFiles:
          - values_dev.yaml
      destinationNamespace: new-caring-event-consumer-dev
      ignoreReplicasDifferences: false

    new-caring-event-consumer-dev2:
      sourcePath: Microservices/Caring/Event/Consumer/new-caring-event-consumer
      sourceHelm:
        valueFiles:
          - values_dev2.yaml
      destinationNamespace: new-caring-event-consumer-dev2
      ignoreReplicasDifferences: false

    caree-notification-dev:
      sourcePath: Microservices/Caring/Scheduler/CareeNotification
      sourceHelm:
        valueFiles:
          - values_dev.yaml
      destinationNamespace: caree-notification-dev
      ignoreReplicasDifferences: false
    # dev ↑↑↑

    # qat ↓↓↓
    # Caring
    new-caring-web-api-qat:
      sourcePath: Microservices/Caring/Backend/Api/new-caring-web-api
      sourceHelm:
        valueFiles:
          - values_qat.yaml
      destinationNamespace: new-caring-web-api-qat
      ignoreReplicasDifferences: false

    new-caring-web-api-qat2:
      sourcePath: Microservices/Caring/Backend/Api/new-caring-web-api
      sourceHelm:
        valueFiles:
          - values_qat2.yaml
      destinationNamespace: new-caring-web-api-qat2
      ignoreReplicasDifferences: false

    new-caring-web-page-qat:
      sourcePath: Microservices/Caring/Frontend/Page/new-caring-web-page
      sourceHelm:
        valueFiles:
          - values_qat.yaml
      destinationNamespace: new-caring-web-page-qat
      ignoreReplicasDifferences: false

    new-caring-mobile-api-qat:
      sourcePath: Microservices/Caring/Backend/Api/new-caring-mobile-api
      sourceHelm:
        valueFiles:
          - values_qat.yaml
      destinationNamespace: new-caring-mobile-api-qat
      ignoreReplicasDifferences: false

    new-caring-event-consumer-qat:
      sourcePath: Microservices/Caring/Event/Consumer/new-caring-event-consumer
      sourceHelm:
        valueFiles:
          - values_qat.yaml
      destinationNamespace: new-caring-event-consumer-qat
      ignoreReplicasDifferences: false

    new-caring-event-consumer-qat2:
      sourcePath: Microservices/Caring/Event/Consumer/new-caring-event-consumer
      sourceHelm:
        valueFiles:
          - values_qat2.yaml
      destinationNamespace: new-caring-event-consumer-qat2
      ignoreReplicasDifferences: false

    caree-notification-qat:
      sourcePath: Microservices/Caring/Scheduler/CareeNotification
      sourceHelm:
        valueFiles:
          - values_qat.yaml
      destinationNamespace: caree-notification-qat
      ignoreReplicasDifferences: false
    # qat ↑↑↑

    # demo ↓↓↓
    # Caring
    new-caring-web-api-demo:
      sourcePath: Microservices/Caring/Backend/Api/new-caring-web-api
      sourceHelm:
        valueFiles:
          - values_demo.yaml
      destinationNamespace: new-caring-web-api-demo
      ignoreReplicasDifferences: false

    new-caring-web-page-demo:
      sourcePath: Microservices/Caring/Frontend/Page/new-caring-web-page
      sourceHelm:
        valueFiles:
          - values_demo.yaml
      destinationNamespace: new-caring-web-page-demo
      ignoreReplicasDifferences: false

    new-caring-mobile-api-demo:
      sourcePath: Microservices/Caring/Backend/Api/new-caring-mobile-api
      sourceHelm:
        valueFiles:
          - values_demo.yaml
      destinationNamespace: new-caring-mobile-api-demo
      ignoreReplicasDifferences: false

    new-caring-event-consumer-demo:
      sourcePath: Microservices/Caring/Event/Consumer/new-caring-event-consumer
      sourceHelm:
        valueFiles:
          - values_demo.yaml
      destinationNamespace: new-caring-event-consumer-demo
      ignoreReplicasDifferences: false

    caree-notification-demo:
      sourcePath: Microservices/Caring/Scheduler/CareeNotification
      sourceHelm:
        valueFiles:
          - values_demo.yaml
      destinationNamespace: caree-notification-demo
      ignoreReplicasDifferences: false
    # demo ↑↑↑

    # release ↓↓↓
    # Caring
    new-caring-web-api-release:
      sourcePath: Microservices/Caring/Backend/Api/new-caring-web-api
      sourceHelm:
        valueFiles:
          - values_release.yaml
      destinationNamespace: new-caring-web-api-release
      ignoreReplicasDifferences: true

    new-caring-web-page-release:
      sourcePath: Microservices/Caring/Frontend/Page/new-caring-web-page
      sourceHelm:
        valueFiles:
          - values_release.yaml
      destinationNamespace: new-caring-web-page-release
      ignoreReplicasDifferences: true

    new-caring-mobile-api-release:
      sourcePath: Microservices/Caring/Backend/Api/new-caring-mobile-api
      sourceHelm:
        valueFiles:
          - values_release.yaml
      destinationNamespace: new-caring-mobile-api-release
      ignoreReplicasDifferences: false

    new-caring-event-consumer-release:
      sourcePath: Microservices/Caring/Event/Consumer/new-caring-event-consumer
      sourceHelm:
        valueFiles:
          - values_release.yaml
      destinationNamespace: new-caring-event-consumer-release
      ignoreReplicasDifferences: true

    caree-notification-release:
      sourcePath: Microservices/Caring/Scheduler/CareeNotification
      sourceHelm:
        valueFiles:
          - values_release.yaml
      destinationNamespace: caree-notification-release
      ignoreReplicasDifferences: false
    # release ↑↑↑

    new-caring-maintenance-page:
      sourcePath: Microservices/Caring/Proxy/maintenance-page-proxy
      sourceHelm:
        valueFiles:
          - values.yaml
      destinationNamespace: new-caring-maintenance-page
      ignoreReplicasDifferences: true

    # github-runner:
    #   sourcePath: Microservices/GitRunner
    #   sourceHelm:
    #     valueFiles:
    #       - values.yaml
    #   destinationNamespace: github-runner
    #   ignoreReplicasDifferences: false

