apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: infra-gateway-internal
spec:
  selector:
    istio: istio
  servers:
    - hosts:
        - "*"
      port:
        name: http
        number: 80
        protocol: HTTP
