apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/neg-auto-creation: "true"
    cloud.google.com/backend-config: '{"ports": {"80": "new-caring-istio-ingressgateway-neg-backendconfig", "15021": "new-caring-istio-ingressgateway-neg-backendconfig"}}'
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "new-caring-istio-ingressgateway-neg-80"}, "15021":{"name": "new-caring-istio-ingressgateway-neg-15021"}}}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"15021":"new-caring-istio-ingressgateway-neg-15021","80":"new-caring-istio-ingressgateway-neg-80"},"zones":["asia-east1-a","asia-east1-b","asia-east1-c"]}'
spec:
  type: ClusterIP
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  ports:
    - name: http2
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: status-port
      protocol: TCP
      port: 15021
      targetPort: 15021
