gateway:
  service:
    # Type of service. Set to "None" to disable the service entirely
    type: LoadBalancer
    ports:
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
    loadBalancerIP: "35.234.29.87" # 先空字串讓 GKE 取得 External IP 之後再回來填上那個 IP
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 500Mi

istiod:
  pilot:
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 1

Settings:
  UseKeycloak: false
  UseStorage: true
  Urls:
    ArgoCD: new-caring-dev-argocd.jubo.health

    # dev ↓↓↓

    # Backend

    # Caring
    DevBackendApiCaring: new-caring-dev-api.jubo.health
    DevBackendApiCaringStorage: new-caring-dev-api-storage.jubo.health

    # Frontend

    # Caring
    DevFrontendCaring: new-caring-dev.jubo.health

    # dev ↑↑↑

    # qat ↓↓↓

    # Backend

    # Caring
    QatBackendApiCaring: new-caring-qat-api.jubo.health
    QatBackendApiCaringStorage: new-caring-qat-api-storage.jubo.health

    # Frontend

    # Caring
    QatFrontendCaring: new-caring-qat.jubo.health

    # qat ↑↑↑

    # demo ↓↓↓

    # Backend

    # Caring
    DemoBackendApiCaring: new-caring-demo-api.jubo.health
    DemoBackendApiCaringStorage: new-caring-demo-api-storage.jubo.health

    # Frontend

    # Caring
    DemoFrontendCaring: new-caring-demo.jubo.health

    # demo ↑↑↑
