gateway:
  service:
    # Type of service. Set to "None" to disable the service entirely
    type: LoadBalancer
    ports:
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
    loadBalancerIP: ""
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 2000m
      memory: 1000Mi

istiod:
  pilot:
    resources:
      requests:
        cpu: 200m
        memory: 2000Mi
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 1

Settings:
  UseStorage: true

  Urls:
    ArgoCD: new-caring-release-argocd.jubo.health

    # Backend

    # Caring
    ReleaseBackendApiCaring: new-caring-release-api.jubo.health
    ReleaseBackendApiCaringStorage: new-caring-release-api-storage.jubo.health

    # Frontend

    # Caring
    ReleaseFrontendCaring: new-caring-release.jubo.health
