App:
  Replicas: 1
  MinReplicas: 1
  MaxReplicas: 1
  Version: 2.0.1.16-dev-4
  UseHPA: false
  UsePDB:
    enabled: false
    UseUnavailable: false # use this should set replicas to 2 above
  Env: Development
  AppResources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1280Mi
  ServiceAccountCredentials: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic3RhdGljLW1hcC0yNDI0MDYiLAogICJwcml2YXRlX2tleV9pZCI6ICIxN2U2YmE3NGRkZjQwZjMxODJmY2MwYWUzYjViMTE4Mjg3MDZhYWVlIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUURCUFFhVUZsM1JlZVE0XG56MnJscCtHVk9XbmI2RERMMFRieENOSkZoZGNCblJlZStsZkgrdGRwZTZuYVZUYUNCdlRVYTdaa2lCREZ6OG4rXG5ua2l0N3ZRNWJqeUxBNzZqN1hESEFPQ2VKVllUVTdlK3JnTlNmUTVLcTVUMXUrc1k2S3QvbmZMSHAxM3kxL04yXG5KTGF5S0tCNDB0RktaWmhaV3NNNm9pTnNVVzQvQkpQWm1Nbml0RWlUV1dXNDc3Q3ZjdnR4ZTRzczhHM3QxYjdFXG5oc2hCU3duR0QzM2trbkMvLzdiZXo3UWVvbGdZbzhSOWZhYzlFWlVScUt6TWtEL0F5Zkh5TWVpZGVoaHpJbEVJXG5LdEhZWms0R0NaL3pEcEVkalQvUkxrWHhDMWdQNEpjb3U5Q3EyTUVHV3FaOVVzRXphZVNWUkI3eXZCUlV3UXZaXG5ZNzc3SHpnN0FnTUJBQUVDZ2dFQUd2M05YRVJaaGgwd0NkZ1RGdWEzR3ZNWGtjTjNoQk5YbmgyODBwV0tLRUZnXG5uM0N1eFR5em9tOXh2MlpWV1o2T0lTNWdjNG9SU2JMU0JMSTlvRlNoekI4cW1XMEVUOUo3Mm0ySmNuTHdUZEozXG5vU0h6b3kzYm9BWWlldkZDT3FCT29EZEM4UUlKbkpaRWZWLzRjdlNRekZUL2d6NzRvNkUxWnVHOG1wc3ZPb3hJXG5vQWwrWmNib2IxNFNzYWZWVDh2RXg5NkRNZ3YrUDRPazF5dENvR0VjZ3JMdjY0SThuS3lQeE9sWCtKYm1rTU5NXG5LMm91ZmEzWmp1SW03c1VuRmVnTjRQb0IrUFRUYVBOcVJxWGVRZVErZFE4NU5xVG9ESDMrOW16NjJCZ3g0MGVtXG4yU0VSMlFlUWRWL1Zwdnc2M2M1R1lNUzUvQnk4Y3dIQ25sbzMzK2FmZlFLQmdRRHhoVFVONG5QZzMwa0N5UWdzXG56WGQ2UjYrZU42b255Yi9zenY1aGs3MTNjZGdZVEp4SVRSY2hmSjU0U29yUmFMdUlFY0hNUG9ZUS9RYm5DVWlYXG4wNDBLQlZWSUNGODUvZzdib1VaTEVOK0E5QlVvSE5IRm5leW9CSkpGV2xGRE1QMStFdzhhbmo5MllCNDgxRHc5XG55Mi9SQjR1bnE1ZTg3cFo0WjlXcXpvSks3UUtCZ1FETTBzeWFFUlFGMFJaVDBNQUltU20xNkNZZkh5bFNVS1YvXG5HbFBybnlBaS85UGNKNHA0R3kwYTR2SlJ5YkUrTTIxNnBiSS9UMlNNZ0VBNysrMFZyME05ME1KLzYzdFVmd2xkXG50cVZmdVIxeUU0R3pKQ2FCZU9leERlQ3A3NVg3dkRDei9Jek8wdVBWYng4NGhDNTZxVXVoNGQvNEpIQ2w0SkNtXG5uWWtBVzRHaXh3S0JnUUNKY1FPckhoWlJmdDkrblVad3NKQndYc0VhNlpTRVJmUlpYOFkxWXl6ci96WTVSY2VlXG5BWGpMVHE2ang4L05zYXNlbVBSUE5ibDNpM1pWSGR4WXdrTzkweUVmOTl1eEZkb0F0SHRiRm9RS1QxeUcwamV5XG5ITmZqR1k3ZnRyRU42cUFuRWRPRGsxQ01IZEMzVHhQbEdwTk1RZDRBa2M2czdwMWtjYnFQRkN2alZRS0JnQmRLXG5NUEdqMTM4QjAyUWNiSG1OME94YVJWdHNrNnBFZVUwR2xWeEpiOElMRFBBUG52TWhRL08yc284U1BCRXlqOVJPXG5Xd0pQNk1NQklreXZ6TG1XZ0RMYk5nS05xQ3huZFkwdVk0ZUs2UW83cFpmVkdIdklYN0FHUC9HU3lKOGpPdlo4XG5WUlovYkdDc2pnUkRJM1hYSWo1NkRKbU9xekJ4WklGTmtISjE5VHVwQW9HQU1sNjFjZVZ0VDhwdzhZcHl2b1AzXG5XYkJOVzdzNE15T3psSWd5d3BWSkZZQXUra21uWml0L3pKRURxVmtIbUE5NEpxb083SlpqcTFxMW9Rc0RwVzlqXG43RnIrcGFUS05JV05DZnM2bmVSc29sYWpPOUl0Q1dqUENTUUdUSmVvc05wUTkrZ0hoRnpTWGo2RUV6N0FGdUl1XG4zYTlTdkFxQWsvMk42cjNGRXNtcm9oWT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJuLWMtYi1hQHN0YXRpYy1tYXAtMjQyNDA2LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwMDc1NTU4MDYzNzAyODM5NDg3OCIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvbi1jLWItYSU0MHN0YXRpYy1tYXAtMjQyNDA2LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9Cg=="
  ConnectionStrings:
    PostgreSqlMaster: "Server=127.0.0.1;Port=5432;Database=caring_dev;Userid=n-c-b-a@static-map-242406.iam;Pooling=true;MinPoolSize=1;MaxPoolSize=100;ConnectionLifeTime=60;"
    PostgreSqlSlave: "Server=127.0.0.1;Port=5432;Database=caring_dev;Userid=n-c-b-a@static-map-242406.iam;Pooling=true;MinPoolSize=1;MaxPoolSize=100;ConnectionLifeTime=60;"
    CHomeConnection: "Server=10.140.15.234,9900;Database=CHOME;User Id=sso_admin;Password=5086@Jubo_SSO@8012;TrustServerCertificate=true;"
    OldCaringConnection: "Server={SERVER},{PORT};Database={DBNAME};User Id=sso_admin;Password=5086@Jubo_SSO@8012;TrustServerCertificate=true;"
  OpenTelemetry:
    EndPoint: "http://opentelemetry-collector.opentelemetry.svc.cluster.local:4317"
    Protocol: "grpc"
  Redis:
    ConnectionString: "jubo-mqtt.asia-east1-b.c.static-map-242406.internal:6379,defaultDatabase=0"
  JCP:
    EndPoint: "http://jcp-dev-api.jubo.health.internal"
    Brand: "JCP"
    Product: "Caring"
    Environment: "dev"
    Name: "caring-dev"
    Version: "1.0.0"
  CloudPubSub:
    ProjectId: "static-map-242406"
    DataSyncTopicId: "caring-dev-data-sync"
    UserActivityLogTopicId: "caring-dev-user-activity-log"
    UserEventHandlingTopicId: "caring-dev-user-event-handling"

SqlProxy:
  Version: 2.18.1
  InstanceName: static-map-242406:asia-east1:caring-dev-pg
  SqlProxyResources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi