apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: new-caring-ingress
  namespace: new-caring-web-page-dev
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/load-balancer-type: "Internal"
spec:
  rules:
    - host: "*"
      http:
        paths:
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: new-caring-web-page
                namespace: new-caring-web-page-dev
                port:
                  number: 80
