apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: new-caring-ingress
  namespace: new-caring-dev
  annotations:
    kubernetes.io/ingress.class: "gce-internal"
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/load-balancer-type: "Internal"
spec:
  rules:
    - host: "*.caringcm.com.tw"
      http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: new-caring-web-api
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: new-caring-web-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: new-caring-web-page
                port:
                  number: 80
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: new-caring-web-page
                port:
                  number: 80
