kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-config
data:
  ASPNETCORE_ENVIRONMENT: "{{ .Values.App.Env }}"

  {{- if .Values.App.ServiceAccountCredentials }}
  GOOGLE_APPLICATION_CREDENTIALS: "/app/secrets/service-account-credentials.json"
  {{- end }}