apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.App.Replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      {{- if .Values.App.ServiceAccountCredentials }}
      volumes:
        - name: secret-sa-volume
          secret:
            secretName: {{ .Chart.Name }}-sa-secret
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "asia-east1-docker.pkg.dev/static-map-242406/new-caring/caring-web-api:{{ .Values.App.Version }}"
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          {{- if .Values.App.ServiceAccountCredentials }}
          volumeMounts:
            - mountPath: /app/secrets
              name: secret-sa-volume
          {{- end }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources: 
{{ toYaml .Values.App.AppResources | indent 11 }}
        - name: cloud-sql-proxy
          image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:{{ .Values.SqlProxy.Version }}"
          args:
            - "--private-ip"
            - "--auto-iam-authn"
            - "--port=5432"
            - "{{ .Values.SqlProxy.InstanceName }}"
          resources: 
            {{- toYaml .Values.SqlProxy.SqlProxyResources | nindent 12 }}
          securityContext:
            # The default Cloud SQL proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true
