{{- if .Values.App.UseHPA }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: new-caring-web-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: new-caring-web-api
  minReplicas: {{ .Values.App.Replicas }}
  maxReplicas: {{ .Values.App.Replicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
      scaleUp:
        selectPolicy: Min
        policies:
          - type: Pods
            value: 1
            periodSeconds: 30
        stabilizationWindowSeconds: 0
      scaleDown:
        selectPolicy: Min
        policies:
          - type: Pods
            value: 1
            periodSeconds: 30
        stabilizationWindowSeconds: 1800
{{- end }}