{{- if .Values.OtelCollector }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-otel-collector
  labels:
    app: {{ .Chart.Name }}-otel-collector
  annotations:
    iam.gke.io/gcp-service-account: "n-c-b-a@static-map-242406.iam.gserviceaccount.com" 
{{ end }}