apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-otel-collector
  labels:
    app: {{ .Chart.Name }}-otel-collector
spec:
  selector:
    app: {{ .Chart.Name }}-otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: metrics
      port: 9464
      targetPort: 9464
    - name: health-check
      port: 13133
      targetPort: 13133
    - name: pprof
      port: 1777
      targetPort: 1777
  type: ClusterIP 