apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-otel-collector-config
  labels:
    app: {{ .Chart.Name }}-otel-collector
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      memory_limiter:
        check_interval: 1s
        limit_mib: 1000
      resource:
        attributes:
          - key: environment
            value: "{{ .Values.App.Env }}"
            action: upsert
          - key: service.name
            value: "{{ .Chart.Name }}"
            action: upsert

    exporters:
      debug:
        verbosity: detailed
      {{- if .Values.OtelCollector.Exporters.JCP }}
      otlp/jcp:
        endpoint: {{ .Values.OtelCollector.Exporters.JCP }}
        tls:
          insecure: true
      {{- end }}
      {{- if .Values.OtelCollector.Exporters.GoogleCloudTrace }}
      googlecloud:
        project: {{ .Values.OtelCollector.Exporters.GoogleCloudTrace.Project }}
        log:
          default_log_name: otel-collector-exported-log
        {{- if .Values.OtelCollector.Exporters.GoogleCloudTrace.SendingQueue }}
        sending_queue:
          enabled: true
          num_consumers: {{ .Values.OtelCollector.Exporters.GoogleCloudTrace.SendingQueue.num_consumers }}
          queue_size: {{ .Values.OtelCollector.Exporters.GoogleCloudTrace.SendingQueue.queue_size }}
        {{- end }}
      {{- end }}

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: 0.0.0.0:1777

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [{{ if .Values.OtelCollector.Exporters.JCP }}otlp/jcp{{ end }}{{ if .Values.OtelCollector.Exporters.GoogleCloudTrace }}, googlecloud{{ end }}]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [{{ if .Values.OtelCollector.Exporters.JCP }}otlp/jcp{{ end }}]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [{{ if .Values.OtelCollector.Exporters.JCP }}otlp/jcp{{ end }}{{ if .Values.OtelCollector.Exporters.GoogleCloudTrace }}, googlecloud{{ end }}]

      extensions: [health_check, pprof]
      telemetry:
        logs:
          level: info