{{- if .Values.App.UsePDB.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: new-caring-web-api-pdb
spec:
{{- if .Values.App.UsePDB.UseUnavailable }}
  maxUnavailable: 1
{{- else }}
  minAvailable: 1
{{- end }}
  selector:
    matchLabels:
      app: new-caring-web-api
{{- end }}