{{- if .Values.App.UsePDB.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}-pdb
spec:
{{- if .Values.App.UsePDB.UseUnavailable }}
  maxUnavailable: 1
{{- else }}
  minAvailable: 1
{{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
{{- end }}