{{- if .Values.App.ServiceAccountCredentials }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-sa-secret
data:
    service-account-credentials.json: {{ .Values.App.ServiceAccountCredentials | quote }}
{{- end }}
