apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.App.ServiceAccount | default "n-c-b-a@static-map-242406.iam.gserviceaccount.com" }}
