kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Chart.Name }}-config"
data:
  ASPNETCORE_ENVIRONMENT: "{{ .Values.App.Env }}"

  ConnectionStrings__PostgreSqlMaster: "{{ .Values.App.ConnectionStrings.PostgreSqlMaster }}"
  ConnectionStrings__PostgreSqlSlave: "{{ .Values.App.ConnectionStrings.PostgreSqlSlave }}"
  ConnectionStrings__CHomeConnection: "{{ .Values.App.ConnectionStrings.CHomeConnection }}"
  ConnectionStrings__OldCaringConnection: "{{ .Values.App.ConnectionStrings.OldCaringConnection }}"
  OpenTelemetry__EndPoint: "{{ .Values.App.OpenTelemetry.EndPoint }}"
  OpenTelemetry__Protocol: "{{ .Values.App.OpenTelemetry.Protocol }}"
  Redis__ConnectionString: "{{ .Values.App.Redis.ConnectionString }}"
  JCP__EndPoint: "{{ .Values.App.JCP.EndPoint }}"
  JCP__Brand: "{{ .Values.App.JCP.Brand }}"
  JCP__Product: "{{ .Values.App.JCP.Product }}"
  JCP__Environment: "{{ .Values.App.JCP.Environment }}"
  JCP__Name: "{{ .Values.App.JCP.Name }}"
  JcpClient__ClientId: "{{ .Values.App.JcpClient.ClientId }}"
  JcpClient__ClientSecret: "{{ .Values.App.JcpClient.ClientSecret }}"
  JcpClient__BaseUrl: "{{ .Values.App.JcpClient.BaseUrl }}"
  JcpClient__Scope: "{{ .Values.App.JcpClient.Scope }}"
  Line__VerifyEndpoint: "{{ .Values.App.Line.VerifyEndpoint }}"
  Line__ChannelId: "{{ .Values.App.Line.ChannelId }}"