apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.App.Replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: caring-web
          image: "asia-east1-docker.pkg.dev/static-map-242406/new-caring/caring-web:{{ .Values.App.Version }}"
          envFrom:
            - configMapRef:
                name: "{{ .Chart.Name }}-config"
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:{{ .Values.App.ContainerPort }}"
          ports:
            - containerPort: {{ .Values.App.ContainerPort }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]
          resources: 
{{ toYaml .Values.App.AppResources | indent 11 }}
        - name: cloud-sql-proxy
          image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:{{ .Values.SqlProxy.Version }}"
          args:
            - "--private-ip"
            - "--auto-iam-authn"
            - "--port=5432"
            - "{{ .Values.SqlProxy.InstanceName }}"
          resources: 
{{ toYaml .Values.SqlProxy.SqlProxyResources | indent 11 }}
          securityContext:
            # The default Cloud SQL proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true
