apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: google-api-destinationrule
spec:
  host: storage.googleapis.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
