App:
  Replicas: 1
  MinReplicas: 1
  MaxReplicas: 1
  Version: 2.0.5.5
  UseHPA: false
  UsePDB:
    enabled: false
    UseUnavailable: false # use this should set replicas to 2 above
  Env: demo
  AppResources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1280Mi
  ServiceAccount: "n-c-b-a@static-map-242406.iam.gserviceaccount.com"
  ConnectionStrings:
    CaringDbContext: "Server=127.0.0.1;Port=5432;Database=caring_demo;Userid=n-c-b-a@static-map-242406.iam;Pooling=true;MinPoolSize=1;MaxPoolSize=100;ConnectionLifeTime=60;"
    CHomeConnection: "Server=10.140.0.40,9900;Database=CHome;User Id=sso_admin;Password=5086@Jubo_SSO@8012;TrustServerCertificate=true;"
    OldCaringConnection: "Server={SERVER},{PORT};Database={DBNAME};User Id=sso_admin;Password=5086@Jubo_SSO@8012;TrustServerCertificate=true;"
  OpenTelemetry:
    EndPoint: "http://127.0.0.1:4317"
    Protocol: "grpc"
  JCP:
    EndPoint: "http://jcp-demo-api.jubo.health.internal"
    Ca: "ShareITN01CA01"
    Cs: "f8f44b836dba473da5a25d908c642f84"
    CaringEndPoint: "https://jcp-demo-api-caring.jubo.health"
    SSOUrl: "https://jcp-demo-sso.jubo.health/caring/login"
    CloudPubSub:
      ProjectId: "jubo-care-platform"
      OrganizationEventHandlingSubscriptionId: "demo_caring_organization_data_sync_sub"
      JcpUserEventHandlingSubscriptionId: "demo_caring_user_data_sync_sub"
      JcpUserPrivilegeEventHandlingSubscriptionId: "demo_organization_user_privilege_sync_caring_sub"
  CloudPubSub:
    ProjectId: "static-map-242406"
    UserActivityLogTopicId: "caring-demo-user-activity-log"
    UserEventHandlingSubscriptionId: "caring-demo-user-event-handling"

SqlProxy:
  Version: 2.18.1
  InstanceName: static-map-242406:asia-east1:caring-dev-pg
  SqlProxyResources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi