App:
  Replicas: 1
  MinReplicas: 1
  MaxReplicas: 1
  Version: 0.0.10
  UseHPA: false
  UsePDB:
    enabled: false
    UseUnavailable: false # use this should set replicas to 2 above
  Env: Development
  AppResources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1280Mi
  ServiceAccount: "n-c-b-a@static-map-242406.iam.gserviceaccount.com"
OpenTelemetry:
  EndPoint: "http://34.81.223.27:14317"
  Protocol: "grpc"
JCP:
  EndPoint: "http://jcp-dev-api.jubo.health.internal"
CloudPubSub:
  ProjectId: "static-map-242406"
  UserActivityLogTopicId: "caring-dev-user-activity-log"
