App:
  Replicas: 1
  MinReplicas: 1
  MaxReplicas: 1
  Version: 2.0.1.16-dev-2
  UseHPA: false
  UsePDB:
    enabled: false
    UseUnavailable: false # use this should set replicas to 2 above
  Env: Development
  AppResources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1280Mi
  ServiceAccount: "n-c-b-a@static-map-242406.iam.gserviceaccount.com"
  ConnectionStrings:
    CaringDbContext: "Server=127.0.0.1;Port=5432;Database=caring_dev;Userid=n-c-b-a@static-map-242406.iam;Pooling=true;MinPoolSize=1;MaxPoolSize=100;ConnectionLifeTime=60;"
    CHomeConnection: "Server=10.140.15.234,9900;Database=CHOME;User Id=sso_admin;Password=5086@Jubo_SSO@8012;TrustServerCertificate=true;"
    OldCaringConnection: "Server={SERVER},{PORT};Database={DBNAME};User Id=sso_admin;Password=5086@Jubo_SSO@8012;TrustServerCertificate=true;"
  OpenTelemetry:
    EndPoint: "http://127.0.0.1:4317"
    Protocol: "grpc"
  JCP:
    EndPoint: "http://jcp-dev-api.jubo.health.internal"
    Ca: "ShareITN01CA01"
    Cs: "f8f44b836dba473da5a25d908c642f84"
  CloudPubSub:
    ProjectId: "static-map-242406"
    UserActivityLogTopicId: "caring-dev-user-activity-log"
    UserEventHandlingSubscriptionId: "caring-dev-user-event-handling"

SqlProxy:
  Version: 2.18.1
  InstanceName: static-map-242406:asia-east1:caring-dev-pg
  SqlProxyResources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi